# Generated by Django 6.0.3 on 2026-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='relase_year',
            new_name='release_year',
        ),
    ]
